### ISSUE TITLE
error

### ISSUE THREAD

**Issue by logan-y-nguyen** [ThoreBor/Anki_Leaderboard#77]
**Describe the bug**
bug happens after a few moments. Here it is:

**Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-15 22:24:44

Exception in thread Thread-115:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "C:\Users\Logan\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 61, in load_leaderboard
    streak, cards, time, cards_past_30_days, retention = Stats()
  File "C:\Users\Logan\AppData\Roaming\Anki2\addons21\41708974\Stats.py", line 13, in Stats
    reviews = mw.col.db.list("SELECT id FROM revlog")
  File "lib\site-packages\anki\db.py", line 81, in list
  File "lib\site-packages\anki\db.py", line 33, in execute
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 30540 and this is thread id 19000.
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Timer(Thread-115, started daemon 19000)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'**

**Steps to reproduce bug**
not much, it just pops up after a bit. i think i did click the second checkbox option at first in config but i have unchecked it since then

**Info**
- Anki version: 2.1.22
- python 3.8.0 Qt 5.14.1 PyQt 5.14.1
- Leaderboard version: Updated 2020-05-07. Only supports Anki 2.1.x.
- Addons: REviewHeatmap, Progress Bar, Pop-up Dictionary beta, Leaderboard, Image Occlusion Enhance for Anki 21 alpha, Heatmap, Frozen Fields, Automatics Basic to Cloze
- OS: windows 10

**Additional context**

**Comment by ThoreBor** [comment]
Looks like you were using the refresh option even though your using Anki 2.1.22. This function only works with Anki 2.1.24 or higher.

**Comment by logan-y-nguyen** [comment]
Thanks yeah. I think that was the issue.

I have a question. How can we create groups? The mcat community could use
one.

Best,
Logan

**Comment by ThoreBor** [comment]
No problem. 
Only I can create groups. I'll add mcat in the next update.
