### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by snafusam** [ThoreBor/Anki_Leaderboard#97]
I'm getting this error while using anki on my mac. I don't know much about coding so I've copied everything below.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-01 20:27:27
Add-ons possibly involved: ⁨Leaderboard⁩

Exception in thread Thread-2089:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "/Users/byronsteele/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 59, in load_leaderboard
    streak, cards, time, cards_past_30_days, retention = Stats()
  File "/Users/byronsteele/Library/Application Support/Anki2/addons21/41708974/Stats.py", line 13, in Stats
    reviews = mw.col.db.list("SELECT id FROM revlog")
  File "anki/db.py", line 81, in list
  File "anki/db.py", line 33, in execute
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4618927552 and this is thread id 123145840410624.
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Timer(Thread-2089, started daemon 123145840410624)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

Other than this error message, the addon works fine. I can continue to use anki without having to restart, and I am still able to reopen the leaderboard without restarting.

**Comment by ThoreBor** [comment]
You've probably enabled the auto-refresh option in the config, but this function only works with Anki 2.1.24+. So you either have to disable it or update Anki (the newest version is 2.1.28 and you're using 2.1.23).
