### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by noseyposey17** [ThoreBor/Anki_Leaderboard#110]
**Describe the bug**
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-13 19:24:03

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Jess\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 26, in Main
    mw.leaderboard = start_main(season_start, season_end)
  File "C:\Users\Jess\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 40, in __init__
    self.setupUI()
  File "C:\Users\Jess\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 79, in setupUI
    leaderboard_on_deck_browser()
  File "C:\Users\Jess\AppData\Roaming\Anki2\addons21\41708974\lb_on_homescreen.py", line 129, in leaderboard_on_deck_browser
    gui_hooks.deck_browser_will_render_content.remove(on_deck_browser_will_render_content)
AttributeError: module 'aqt.gui_hooks' has no attribute 'deck_browser_will_render_content'

I couldn't get Leaderboard to work on Anki 2.1.15 so I updated to 2.1.20 now I'm getting a different error.

**Comment by ThoreBor** [comment]
Disabling "Show leaderboard on homescreen", or updating to the most recent Anki version should fix the issue. I thought that this would work on 2.1.20 and up, but apparently it doesn't.

**Comment by noseyposey17** [comment]
Thank you that worked. Does this add-on work with Anki 2.1.15? I want to use it with another computer but I don't want to upgrade. I am getting an error with it.
